env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
ecmaVersion: 2020
  ecmaVersion: latest
  sourceType: module
rules: { no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]}
